// AUTO-GENERATED by scripts/download-frames.mjs — do not edit manually
import type { FrameItem } from './frameService'

export const STATIC_FRAMES: FrameItem[] = [
  {
    "id": 66,
    "filename": "6852977303afd.png",
    "name": "Se Điếu",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 68,
    "filename": "68529b5bf0b08.png",
    "name": "Việt Nam",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 69,
    "filename": "68529b8f964a4.png",
    "name": "HelloKitty",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 70,
    "filename": "68529ba92966b.png",
    "name": "HelloKitty",
    "frame": "bigrectangle",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 74,
    "filename": "68529bdb96806.png",
    "name": "Porsche",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 75,
    "filename": "68529c39b1183.png",
    "name": "Y2K",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 76,
    "filename": "68529c57c0a28.png",
    "name": "Instagram",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 77,
    "filename": "68529c7e26d92.png",
    "name": "Lucky",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 78,
    "filename": "68529c87567eb.png",
    "name": "Lucky",
    "frame": "bigrectangle",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 80,
    "filename": "68529cb7c6d04.png",
    "name": "Powerpuff",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 81,
    "filename": "68529ccce2380.png",
    "name": "shinnosuke",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 84,
    "filename": "68529cfb9748d.png",
    "name": "Jeans",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 85,
    "filename": "68529d0432f42.png",
    "name": "Jeans",
    "frame": "bigrectangle",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 87,
    "filename": "68529d1e59ef8.png",
    "name": "Powerpuff",
    "frame": "bigrectangle",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 88,
    "filename": "68529d27481d8.png",
    "name": "shinosuke",
    "frame": "bigrectangle",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 91,
    "filename": "68529db67f80e.png",
    "name": "Y2K",
    "frame": "bigrectangle",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 95,
    "filename": "68529e3629737.png",
    "name": "Netflix",
    "frame": "bigrectangle",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 105,
    "filename": "6852d138ea7bf.png",
    "name": "BearBare",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 107,
    "filename": "6852d220360a8.png",
    "name": "Loopy",
    "frame": "bigrectangle",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 108,
    "filename": "6852d238938b9.png",
    "name": "Loopy",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 118,
    "filename": "6854e5408664d.png",
    "name": "Giấy Kết Hôn",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 123,
    "filename": "6856bf7547184.png",
    "name": "EmXinhSayHi",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 129,
    "filename": "6857dd9fcbe9d.png",
    "name": "Basic-5",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 133,
    "filename": "685a41b84c9e3.png",
    "name": "Basic-6",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 138,
    "filename": "6864a24e4b7e2.png",
    "name": "Minion",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 150,
    "filename": "686f38fecdb0d.png",
    "name": "GenG",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 152,
    "filename": "686f44ca41c86.png",
    "name": "Stitch",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 155,
    "filename": "686f84a47a36d.png",
    "name": "Meme",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 167,
    "filename": "686fe53db6dfc.png",
    "name": "MatchaLatte",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 170,
    "filename": "68707f70636a1.png",
    "name": "Conan",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 175,
    "filename": "6873abf8e3917.png",
    "name": "Vintage1",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 176,
    "filename": "6873ac02ab5a1.png",
    "name": "Vintage2",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 184,
    "filename": "68770830ddc58.png",
    "name": "BearPink",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 185,
    "filename": "687779c79d107.png",
    "name": "BunBoHue",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 192,
    "filename": "687cc3f5c3958.png",
    "name": "ĐÙ MÁ",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 195,
    "filename": "687cd152e026d.png",
    "name": "Chiikawa",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 197,
    "filename": "687f0219ebe02.png",
    "name": "Gumball",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 206,
    "filename": "688a37a6b673c.png",
    "name": "Amazing",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 223,
    "filename": "689801c6ac302.png",
    "name": "Quốc Khánh 2/9",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 224,
    "filename": "689ab7bec5d76.png",
    "name": "WeAreOne",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 231,
    "filename": "689b4afcb36f1.png",
    "name": "Cinnamoroll",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 237,
    "filename": "689da03a3127c.png",
    "name": "Thư",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 248,
    "filename": "68a3d8f16c61d.png",
    "name": "IOS",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 252,
    "filename": "68a463c666438.png",
    "name": "QH MasterD",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 264,
    "filename": "68a98cd549993.png",
    "name": "UEder",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học"
  },
  {
    "id": 265,
    "filename": "68a98d0834147.png",
    "name": "Juky San",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 269,
    "filename": "68aa0dcb8dfa1.png",
    "name": "Wxrdie",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 270,
    "filename": "68ab39da93cd1.png",
    "name": "FanNCT_DREAM",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 276,
    "filename": "68b0244e76e35.png",
    "name": "DPR IAN",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 278,
    "filename": "68b0907158035.png",
    "name": "AnhTraiSayHi",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 297,
    "filename": "68c3fdcb527e5.png",
    "name": "Amazing",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 298,
    "filename": "68c400b3d9470.png",
    "name": "Hello Kitty",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 311,
    "filename": "68d0dd9bb3a08.png",
    "name": "Cutie Pinkie",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 312,
    "filename": "68d50f3783378.png",
    "name": "Dâu Tây",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 314,
    "filename": "68d89ad14df35.png",
    "name": "Retro Windows",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 316,
    "filename": "68d8f10969679.png",
    "name": "ShinChanPink",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 317,
    "filename": "68d98e7b4884e.png",
    "name": "Retro Windows",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 319,
    "filename": "68dbb8968a7c0.png",
    "name": "School",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 320,
    "filename": "68dc652f832fc.png",
    "name": "ÁnhSángAZA",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 325,
    "filename": "68dcc60a4897c.png",
    "name": "XinhhAirlines",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 327,
    "filename": "68dcc67d7e7ab.png",
    "name": "XinhhAirlines",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 333,
    "filename": "68dd4388c0191.png",
    "name": "ToyStory",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 334,
    "filename": "68dd4f8543881.png",
    "name": "TV",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 335,
    "filename": "68df3dfdefc22.png",
    "name": "Basic-5",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 336,
    "filename": "68df3e1149dce.png",
    "name": "Basic-4",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 337,
    "filename": "68df3e1e7dabf.png",
    "name": "Basic-3",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 338,
    "filename": "68df3ed02d775.png",
    "name": "Basic-2",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 339,
    "filename": "68df3f19d9d3f.png",
    "name": "Basic-1",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 340,
    "filename": "68df4196da89b.png",
    "name": "Basic-1",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 341,
    "filename": "68df41b70eb0e.png",
    "name": "Basic-2",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 342,
    "filename": "68df41df4934f.png",
    "name": "Basic-7",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 343,
    "filename": "68df420421b73.png",
    "name": "Basic-8",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 345,
    "filename": "68df4242dfa05.png",
    "name": "Basic-11",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 346,
    "filename": "68df42a174a8d.png",
    "name": "Basic-10",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 347,
    "filename": "68df435872c67.png",
    "name": "Basic-6",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 348,
    "filename": "68df437c5f891.png",
    "name": "Basic-7",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 349,
    "filename": "68df473214183.png",
    "name": "Basic-1",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 350,
    "filename": "68df474dba196.png",
    "name": "Basic-2",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 351,
    "filename": "68df4764cfc2b.png",
    "name": "Basic-3",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 352,
    "filename": "68df477dd5360.png",
    "name": "Basic-4",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 353,
    "filename": "68df47965d96e.png",
    "name": "Basic-5",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 354,
    "filename": "68df47ae9c158.png",
    "name": "Basic-6",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 358,
    "filename": "68e471275df2c.png",
    "name": "Colorful",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 364,
    "filename": "68e4dff09e6d5.png",
    "name": "Jisoo",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 365,
    "filename": "68e4e44d42393.png",
    "name": "BlackPink",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 375,
    "filename": "68e67ec98245f.png",
    "name": "Jin(BTS)",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 377,
    "filename": "68e73af797a67.png",
    "name": "Jimin(BTS)",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 379,
    "filename": "68e8e901bae50.png",
    "name": "Girly",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 385,
    "filename": "68ecec87142ee.png",
    "name": "Tinder",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 386,
    "filename": "68f20a3689a97.png",
    "name": "BAV",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học"
  },
  {
    "id": 387,
    "filename": "68f213652773c.png",
    "name": "AOF",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học"
  },
  {
    "id": 388,
    "filename": "68f2143f188f8.png",
    "name": "FTU",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học"
  },
  {
    "id": 389,
    "filename": "68f215d332a18.png",
    "name": "NEU",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học"
  },
  {
    "id": 390,
    "filename": "68f216916ea97.png",
    "name": "HNUE",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học"
  },
  {
    "id": 413,
    "filename": "68f762788685d.png",
    "name": "Dear Phúc Nguyên",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 427,
    "filename": "68fdab4e38d77.png",
    "name": "ZEUS TBTW",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 431,
    "filename": "69020f0f64a7c.png",
    "name": "HAU",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học"
  },
  {
    "id": 441,
    "filename": "69024313f210d.png",
    "name": "V(BTS)",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 455,
    "filename": "69097d8bcc7b7.png",
    "name": "Magazine",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 461,
    "filename": "690dcf7ed31b6.png",
    "name": "TMU",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học"
  },
  {
    "id": 462,
    "filename": "690dd37aca67e.png",
    "name": "HMU",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học"
  },
  {
    "id": 465,
    "filename": "6910bc26e14da.png",
    "name": "ParkBoGum",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 470,
    "filename": "6921c4526b985.png",
    "name": "Steven Universe",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 471,
    "filename": "6921c4677562b.png",
    "name": "matcha",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 472,
    "filename": "6928ddb90cc97.png",
    "name": "cream-soda",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 473,
    "filename": "6928ddc669493.png",
    "name": "cream-soda",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 474,
    "filename": "6929d01fd3d8c.png",
    "name": "glorious.blue.eyed.king",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 478,
    "filename": "692c31d942db2.png",
    "name": "Martin",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 479,
    "filename": "692c32375296f.png",
    "name": "Keonho",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 482,
    "filename": "692d7d65603ca.png",
    "name": "Basic-5",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 483,
    "filename": "692d81cfb1e9f.png",
    "name": "Theater Ticket",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 484,
    "filename": "692d8418563a1.png",
    "name": "Zootopia",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 486,
    "filename": "692e9bec9d990.png",
    "name": "BMKTCR x \"BÁO\" THỨC IN ĐẬM INDIE",
    "frame": "square",
    "categoryId": 97804,
    "categoryName": "Frame Sự Kiện"
  },
  {
    "id": 491,
    "filename": "692ed2cc19d03.png",
    "name": "Locket",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 492,
    "filename": "692edb205f3f0.png",
    "name": "seonghyeon",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 493,
    "filename": "69310c3abb836.png",
    "name": "Merry Chirstmas 🎅🏻",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 495,
    "filename": "69310e3a32eac.png",
    "name": "Merry Chirstmas 🎅🏻",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 496,
    "filename": "6933cabb1dd7d.png",
    "name": "DẤU VÂN TAY x \"BÁO\" THỨC IN ĐẬM INDIE",
    "frame": "square",
    "categoryId": 97804,
    "categoryName": "Frame Sự Kiện"
  },
  {
    "id": 500,
    "filename": "69403bba702c9.png",
    "name": "CHIPANDCOD x \"BÁO\" THỨC IN ĐẬM INDIE",
    "frame": "square",
    "categoryId": 97804,
    "categoryName": "Frame Sự Kiện"
  },
  {
    "id": 504,
    "filename": "694f7262a03db.png",
    "name": "Girly",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 506,
    "filename": "69567d1275bf7.png",
    "name": "Magazine",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 507,
    "filename": "69567d8355fe2.png",
    "name": "2026",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 508,
    "filename": "69567e9b50731.png",
    "name": "Jang Wonyoung",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol"
  },
  {
    "id": 509,
    "filename": "69567fdb48069.png",
    "name": "2026",
    "frame": "bigrectangle",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 510,
    "filename": "69573a0edf0dc.png",
    "name": "Báo Xuân Bính Ngọ",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 511,
    "filename": "695b91d10ae9f.png",
    "name": "Doggo's Day",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 515,
    "filename": "696a75a998902.png",
    "name": "UmTi9thdebut",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 522,
    "filename": "698eb32be5f3e.png",
    "name": "tripleS 3rd anniversary",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 524,
    "filename": "6992b4f935784.png",
    "name": "digitalcam cartoon",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 525,
    "filename": "6999b129e6732.png",
    "name": "⪩. .⪨ 𝐂𝐞𝐥𝐞𝐛𝐫𝐚𝐭𝐞 “𝓟𝓮𝓪𝓷𝓾𝓽” 𝟏𝟏𝐭𝐡 𝐝𝐞𝐛𝐮𝐭: 🥜",
    "frame": "square",
    "categoryId": 97804,
    "categoryName": "Frame Sự Kiện"
  },
  {
    "id": 526,
    "filename": "699c22078a038.png",
    "name": "Shane Hollander",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 528,
    "filename": "699e0fa10f0f8.png",
    "name": "HLE25 x camjack",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 529,
    "filename": "699e172e8caa3.png",
    "name": "LLYA Rozanov",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 530,
    "filename": "699e18009131a.png",
    "name": "Hoàng Yến Chibi",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 531,
    "filename": "699e18607041b.png",
    "name": "Dương Domic",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 532,
    "filename": "69ac4f1c3282f.png",
    "name": "아가공'𝑠 𝑂𝑑𝑦𝑠𝑠𝑒𝑦 — ZEKA",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 533,
    "filename": "69ac4f2346868.png",
    "name": "아가공'𝑠 𝑂𝑑𝑦𝑠𝑠𝑒𝑦 — ZEKA",
    "frame": "grid",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 534,
    "filename": "69ae27bd104bf.png",
    "name": "thomeo",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon"
  },
  {
    "id": 535,
    "filename": "69ae27cf2e4e8.png",
    "name": "Pháp Kiều",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 536,
    "filename": "69ae287abfeb9.png",
    "name": "Phúc Nguyên",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa"
  },
  {
    "id": 537,
    "filename": "69ae2892b1b59.png",
    "name": "Birthday Party",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️"
  },
  {
    "id": 538,
    "filename": "69ae28ab885ab.png",
    "name": "Save the date",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 539,
    "filename": "69ae28bd7352b.png",
    "name": "star1",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 540,
    "filename": "69ae28caab9c6.png",
    "name": "star2",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 541,
    "filename": "69ae2913e9287.png",
    "name": "star3",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  },
  {
    "id": 542,
    "filename": "69ae292690b2f.png",
    "name": "hpbd",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic"
  }
]
