// AUTO-GENERATED by scripts/download-frames.mjs + detect-slots.mjs — do not edit manually
import type { FrameItem } from './frameService'

export const STATIC_FRAMES: FrameItem[] = [
  {
    "id": 66,
    "filename": "6852977303afd.png",
    "name": "Se Điếu",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 5,
    "slots_data": [
      {
        "x": 56,
        "y": 56,
        "w": 772,
        "h": 580
      },
      {
        "x": 56,
        "y": 672,
        "w": 772,
        "h": 580
      },
      {
        "x": 56,
        "y": 1288,
        "w": 772,
        "h": 576
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 572
      },
      {
        "x": 652,
        "y": 2248,
        "w": 176,
        "h": 132
      }
    ]
  },
  {
    "id": 68,
    "filename": "68529b5bf0b08.png",
    "name": "Việt Nam",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 672,
        "w": 772,
        "h": 576
      },
      {
        "x": 56,
        "y": 1292,
        "w": 772,
        "h": 572
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 568
      }
    ]
  },
  {
    "id": 69,
    "filename": "68529b8f964a4.png",
    "name": "HelloKitty",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1908,
        "w": 768,
        "h": 568
      }
    ]
  },
  {
    "id": 70,
    "filename": "68529ba92966b.png",
    "name": "HelloKitty",
    "frame": "bigrectangle",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 388
      },
      {
        "x": 572,
        "y": 440,
        "w": 524,
        "h": 392
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 848,
        "w": 524,
        "h": 392
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 392
      }
    ]
  },
  {
    "id": 74,
    "filename": "68529bdb96806.png",
    "name": "Porsche",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1908,
        "w": 768,
        "h": 560
      }
    ]
  },
  {
    "id": 75,
    "filename": "68529c39b1183.png",
    "name": "Y2K",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 56,
        "w": 768,
        "h": 584
      },
      {
        "x": 56,
        "y": 672,
        "w": 772,
        "h": 580
      },
      {
        "x": 56,
        "y": 1288,
        "w": 768,
        "h": 580
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 572
      }
    ]
  },
  {
    "id": 76,
    "filename": "68529c57c0a28.png",
    "name": "Instagram",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 52,
        "w": 768,
        "h": 560
      },
      {
        "x": 56,
        "y": 668,
        "w": 768,
        "h": 560
      },
      {
        "x": 56,
        "y": 1284,
        "w": 768,
        "h": 560
      },
      {
        "x": 56,
        "y": 1908,
        "w": 768,
        "h": 560
      }
    ]
  },
  {
    "id": 77,
    "filename": "68529c7e26d92.png",
    "name": "Lucky",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1908,
        "w": 772,
        "h": 568
      }
    ]
  },
  {
    "id": 78,
    "filename": "68529c87567eb.png",
    "name": "Lucky",
    "frame": "bigrectangle",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 388
      },
      {
        "x": 572,
        "y": 440,
        "w": 524,
        "h": 392
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 392
      }
    ]
  },
  {
    "id": 80,
    "filename": "68529cb7c6d04.png",
    "name": "Powerpuff",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 72,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 64,
        "y": 1296,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1916,
        "w": 756,
        "h": 552
      }
    ]
  },
  {
    "id": 81,
    "filename": "68529ccce2380.png",
    "name": "shinnosuke",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 72,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 64,
        "y": 1296,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1916,
        "w": 756,
        "h": 552
      }
    ]
  },
  {
    "id": 84,
    "filename": "68529cfb9748d.png",
    "name": "Jeans",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1908,
        "w": 772,
        "h": 568
      }
    ]
  },
  {
    "id": 85,
    "filename": "68529d0432f42.png",
    "name": "Jeans",
    "frame": "bigrectangle",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 6,
    "slots_data": [
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 32,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 440,
        "w": 520,
        "h": 388
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 392
      }
    ]
  },
  {
    "id": 87,
    "filename": "68529d1e59ef8.png",
    "name": "Powerpuff",
    "frame": "bigrectangle",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 6,
    "slots_data": [
      {
        "x": 32,
        "y": 32,
        "w": 512,
        "h": 384
      },
      {
        "x": 576,
        "y": 32,
        "w": 516,
        "h": 384
      },
      {
        "x": 576,
        "y": 444,
        "w": 516,
        "h": 384
      },
      {
        "x": 32,
        "y": 448,
        "w": 512,
        "h": 380
      },
      {
        "x": 32,
        "y": 860,
        "w": 512,
        "h": 384
      },
      {
        "x": 576,
        "y": 860,
        "w": 516,
        "h": 384
      }
    ]
  },
  {
    "id": 88,
    "filename": "68529d27481d8.png",
    "name": "shinosuke",
    "frame": "bigrectangle",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 6,
    "slots_data": [
      {
        "x": 32,
        "y": 32,
        "w": 512,
        "h": 384
      },
      {
        "x": 576,
        "y": 32,
        "w": 516,
        "h": 384
      },
      {
        "x": 576,
        "y": 444,
        "w": 516,
        "h": 384
      },
      {
        "x": 32,
        "y": 448,
        "w": 512,
        "h": 380
      },
      {
        "x": 32,
        "y": 860,
        "w": 512,
        "h": 384
      },
      {
        "x": 576,
        "y": 860,
        "w": 516,
        "h": 384
      }
    ]
  },
  {
    "id": 91,
    "filename": "68529db67f80e.png",
    "name": "Y2K",
    "frame": "bigrectangle",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 392
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 444,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 388
      }
    ]
  },
  {
    "id": 95,
    "filename": "68529e3629737.png",
    "name": "Netflix",
    "frame": "bigrectangle",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 88,
        "w": 520,
        "h": 332
      },
      {
        "x": 572,
        "y": 88,
        "w": 524,
        "h": 332
      },
      {
        "x": 28,
        "y": 440,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 444,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 388
      }
    ]
  },
  {
    "id": 105,
    "filename": "6852d138ea7bf.png",
    "name": "BearBare",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 56,
        "w": 772,
        "h": 580
      },
      {
        "x": 56,
        "y": 672,
        "w": 772,
        "h": 592
      },
      {
        "x": 80,
        "y": 1304,
        "w": 748,
        "h": 560
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 572
      }
    ]
  },
  {
    "id": 107,
    "filename": "6852d220360a8.png",
    "name": "Loopy",
    "frame": "bigrectangle",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 392
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 444,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 388
      }
    ]
  },
  {
    "id": 108,
    "filename": "6852d238938b9.png",
    "name": "Loopy",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 56,
        "w": 772,
        "h": 580
      },
      {
        "x": 56,
        "y": 680,
        "w": 772,
        "h": 572
      },
      {
        "x": 56,
        "y": 1296,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 572
      }
    ]
  },
  {
    "id": 118,
    "filename": "6854e5408664d.png",
    "name": "Giấy Kết Hôn",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 76,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 68,
        "y": 1296,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1908,
        "w": 756,
        "h": 552
      }
    ]
  },
  {
    "id": 123,
    "filename": "6856bf7547184.png",
    "name": "EmXinhSayHi",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 76,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 68,
        "y": 1296,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1908,
        "w": 756,
        "h": 548
      }
    ]
  },
  {
    "id": 129,
    "filename": "6857dd9fcbe9d.png",
    "name": "Basic-5",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 72,
        "w": 756,
        "h": 552
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 68,
        "y": 1296,
        "w": 756,
        "h": 552
      },
      {
        "x": 64,
        "y": 1908,
        "w": 756,
        "h": 552
      }
    ]
  },
  {
    "id": 133,
    "filename": "685a41b84c9e3.png",
    "name": "Basic-6",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 64,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 60,
        "y": 1900,
        "w": 768,
        "h": 564
      }
    ]
  },
  {
    "id": 138,
    "filename": "6864a24e4b7e2.png",
    "name": "Minion",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 64,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 60,
        "y": 1900,
        "w": 768,
        "h": 564
      }
    ]
  },
  {
    "id": 150,
    "filename": "686f38fecdb0d.png",
    "name": "GenG",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 76,
        "w": 756,
        "h": 548
      },
      {
        "x": 68,
        "y": 688,
        "w": 752,
        "h": 548
      },
      {
        "x": 72,
        "y": 1300,
        "w": 752,
        "h": 544
      },
      {
        "x": 68,
        "y": 1908,
        "w": 752,
        "h": 548
      }
    ]
  },
  {
    "id": 152,
    "filename": "686f44ca41c86.png",
    "name": "Stitch",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 76,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 68,
        "y": 1296,
        "w": 752,
        "h": 548
      },
      {
        "x": 64,
        "y": 1908,
        "w": 756,
        "h": 548
      }
    ]
  },
  {
    "id": 155,
    "filename": "686f84a47a36d.png",
    "name": "Meme",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 96,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 64,
        "y": 1296,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1908,
        "w": 756,
        "h": 548
      }
    ]
  },
  {
    "id": 167,
    "filename": "686fe53db6dfc.png",
    "name": "MatchaLatte",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1908,
        "w": 772,
        "h": 568
      }
    ]
  },
  {
    "id": 170,
    "filename": "68707f70636a1.png",
    "name": "Conan",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 72,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 692,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1308,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1932,
        "w": 756,
        "h": 548
      }
    ]
  },
  {
    "id": 175,
    "filename": "6873abf8e3917.png",
    "name": "Vintage1",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 56,
        "y": 1292,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 1908,
        "w": 772,
        "h": 568
      }
    ]
  },
  {
    "id": 176,
    "filename": "6873ac02ab5a1.png",
    "name": "Vintage2",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1908,
        "w": 772,
        "h": 568
      }
    ]
  },
  {
    "id": 184,
    "filename": "68770830ddc58.png",
    "name": "BearPink",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 680,
        "w": 768,
        "h": 564
      },
      {
        "x": 60,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1912,
        "w": 772,
        "h": 560
      }
    ]
  },
  {
    "id": 185,
    "filename": "687779c79d107.png",
    "name": "BunBoHue",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 76,
        "w": 752,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 68,
        "y": 1296,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1908,
        "w": 756,
        "h": 548
      }
    ]
  },
  {
    "id": 192,
    "filename": "687cc3f5c3958.png",
    "name": "ĐÙ MÁ",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 164,
        "w": 772,
        "h": 464
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1908,
        "w": 772,
        "h": 568
      }
    ]
  },
  {
    "id": 195,
    "filename": "687cd152e026d.png",
    "name": "Chiikawa",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 5,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 236,
        "y": 676,
        "w": 304,
        "h": 124
      },
      {
        "x": 60,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1908,
        "w": 772,
        "h": 568
      }
    ]
  },
  {
    "id": 197,
    "filename": "687f0219ebe02.png",
    "name": "Gumball",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1908,
        "w": 772,
        "h": 568
      }
    ]
  },
  {
    "id": 206,
    "filename": "688a37a6b673c.png",
    "name": "Amazing",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 68,
        "y": 72,
        "w": 748,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1296,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1908,
        "w": 756,
        "h": 548
      }
    ]
  },
  {
    "id": 223,
    "filename": "689801c6ac302.png",
    "name": "Quốc Khánh 2/9",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 672,
        "w": 772,
        "h": 576
      },
      {
        "x": 56,
        "y": 1292,
        "w": 772,
        "h": 572
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 568
      }
    ]
  },
  {
    "id": 224,
    "filename": "689ab7bec5d76.png",
    "name": "WeAreOne",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 64,
        "w": 764,
        "h": 556
      },
      {
        "x": 60,
        "y": 680,
        "w": 764,
        "h": 560
      },
      {
        "x": 60,
        "y": 1292,
        "w": 764,
        "h": 556
      },
      {
        "x": 60,
        "y": 1912,
        "w": 764,
        "h": 560
      }
    ]
  },
  {
    "id": 231,
    "filename": "689b4afcb36f1.png",
    "name": "Cinnamoroll",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 680,
        "w": 768,
        "h": 564
      },
      {
        "x": 60,
        "y": 1296,
        "w": 768,
        "h": 564
      },
      {
        "x": 60,
        "y": 1912,
        "w": 768,
        "h": 560
      }
    ]
  },
  {
    "id": 237,
    "filename": "689da03a3127c.png",
    "name": "Thư",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 3,
    "slots_data": [
      {
        "x": 68,
        "y": 60,
        "w": 748,
        "h": 536
      },
      {
        "x": 68,
        "y": 684,
        "w": 748,
        "h": 532
      },
      {
        "x": 68,
        "y": 1304,
        "w": 748,
        "h": 536
      }
    ]
  },
  {
    "id": 248,
    "filename": "68a3d8f16c61d.png",
    "name": "IOS",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 72,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 64,
        "y": 1296,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1916,
        "w": 756,
        "h": 552
      }
    ]
  },
  {
    "id": 252,
    "filename": "68a463c666438.png",
    "name": "QH MasterD",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 5,
    "slots_data": [
      {
        "x": 60,
        "y": 64,
        "w": 764,
        "h": 556
      },
      {
        "x": 60,
        "y": 680,
        "w": 764,
        "h": 560
      },
      {
        "x": 736,
        "y": 1000,
        "w": 88,
        "h": 240
      },
      {
        "x": 60,
        "y": 1292,
        "w": 764,
        "h": 556
      },
      {
        "x": 60,
        "y": 1912,
        "w": 764,
        "h": 560
      }
    ]
  },
  {
    "id": 264,
    "filename": "68a98cd549993.png",
    "name": "UEder",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học",
    "slots": 9,
    "slots_data": [
      {
        "x": 176,
        "y": 140,
        "w": 2404,
        "h": 1768
      },
      {
        "x": 176,
        "y": 2084,
        "w": 2328,
        "h": 1764
      },
      {
        "x": 976,
        "y": 2084,
        "w": 832,
        "h": 552
      },
      {
        "x": 1788,
        "y": 2724,
        "w": 792,
        "h": 1124
      },
      {
        "x": 176,
        "y": 2800,
        "w": 1052,
        "h": 1048
      },
      {
        "x": 176,
        "y": 4024,
        "w": 2404,
        "h": 1764
      },
      {
        "x": 172,
        "y": 5964,
        "w": 576,
        "h": 1764
      },
      {
        "x": 324,
        "y": 5964,
        "w": 2168,
        "h": 1764
      },
      {
        "x": 2056,
        "y": 7140,
        "w": 524,
        "h": 588
      }
    ]
  },
  {
    "id": 265,
    "filename": "68a98d0834147.png",
    "name": "Juky San",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 60,
        "y": 72,
        "w": 764,
        "h": 552
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 548
      },
      {
        "x": 72,
        "y": 1304,
        "w": 740,
        "h": 536
      },
      {
        "x": 72,
        "y": 1916,
        "w": 756,
        "h": 524
      }
    ]
  },
  {
    "id": 269,
    "filename": "68aa0dcb8dfa1.png",
    "name": "Wxrdie",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 56,
        "w": 772,
        "h": 580
      },
      {
        "x": 56,
        "y": 672,
        "w": 772,
        "h": 576
      },
      {
        "x": 56,
        "y": 1288,
        "w": 772,
        "h": 576
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 572
      }
    ]
  },
  {
    "id": 270,
    "filename": "68ab39da93cd1.png",
    "name": "FanNCT_DREAM",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 120,
        "y": 136,
        "w": 1636,
        "h": 1160
      },
      {
        "x": 120,
        "y": 1436,
        "w": 1632,
        "h": 1180
      },
      {
        "x": 120,
        "y": 2740,
        "w": 1636,
        "h": 1196
      },
      {
        "x": 120,
        "y": 4056,
        "w": 1632,
        "h": 1184
      }
    ]
  },
  {
    "id": 276,
    "filename": "68b0244e76e35.png",
    "name": "DPR IAN",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 768,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 564
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1908,
        "w": 768,
        "h": 568
      }
    ]
  },
  {
    "id": 278,
    "filename": "68b0907158035.png",
    "name": "AnhTraiSayHi",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 60,
        "y": 52,
        "w": 764,
        "h": 556
      },
      {
        "x": 60,
        "y": 672,
        "w": 764,
        "h": 556
      },
      {
        "x": 60,
        "y": 1292,
        "w": 764,
        "h": 556
      },
      {
        "x": 60,
        "y": 1912,
        "w": 760,
        "h": 556
      }
    ]
  },
  {
    "id": 297,
    "filename": "68c3fdcb527e5.png",
    "name": "Amazing",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 44,
        "y": 768,
        "w": 512,
        "h": 680
      },
      {
        "x": 588,
        "y": 768,
        "w": 508,
        "h": 680
      }
    ]
  },
  {
    "id": 298,
    "filename": "68c400b3d9470.png",
    "name": "Hello Kitty",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 508,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 684
      },
      {
        "x": 588,
        "y": 764,
        "w": 508,
        "h": 684
      }
    ]
  },
  {
    "id": 311,
    "filename": "68d0dd9bb3a08.png",
    "name": "Cutie Pinkie",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 72,
        "w": 756,
        "h": 552
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 64,
        "y": 1296,
        "w": 756,
        "h": 552
      },
      {
        "x": 64,
        "y": 1908,
        "w": 756,
        "h": 552
      }
    ]
  },
  {
    "id": 312,
    "filename": "68d50f3783378.png",
    "name": "Dâu Tây",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 96,
        "w": 772,
        "h": 532
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 56,
        "y": 1292,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 314,
    "filename": "68d89ad14df35.png",
    "name": "Retro Windows",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 68,
        "y": 152,
        "w": 748,
        "h": 448
      },
      {
        "x": 84,
        "y": 728,
        "w": 720,
        "h": 468
      },
      {
        "x": 68,
        "y": 1368,
        "w": 748,
        "h": 476
      },
      {
        "x": 60,
        "y": 1912,
        "w": 764,
        "h": 460
      }
    ]
  },
  {
    "id": 316,
    "filename": "68d8f10969679.png",
    "name": "ShinChanPink",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 72,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1296,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1916,
        "w": 756,
        "h": 548
      }
    ]
  },
  {
    "id": 317,
    "filename": "68d98e7b4884e.png",
    "name": "Retro Windows",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 592,
        "y": 48,
        "w": 504,
        "h": 608
      },
      {
        "x": 52,
        "y": 120,
        "w": 496,
        "h": 604
      },
      {
        "x": 64,
        "y": 840,
        "w": 468,
        "h": 592
      },
      {
        "x": 592,
        "y": 848,
        "w": 500,
        "h": 592
      }
    ]
  },
  {
    "id": 319,
    "filename": "68dbb8968a7c0.png",
    "name": "School",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 112,
        "y": 156,
        "w": 540,
        "h": 408
      },
      {
        "x": 56,
        "y": 660,
        "w": 772,
        "h": 564
      },
      {
        "x": 96,
        "y": 1292,
        "w": 692,
        "h": 572
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 320,
    "filename": "68dc652f832fc.png",
    "name": "ÁnhSángAZA",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 176,
        "y": 212,
        "w": 2392,
        "h": 1744
      },
      {
        "x": 68,
        "y": 2072,
        "w": 2560,
        "h": 1888
      },
      {
        "x": 176,
        "y": 4044,
        "w": 2392,
        "h": 1744
      },
      {
        "x": 92,
        "y": 5908,
        "w": 2560,
        "h": 1876
      }
    ]
  },
  {
    "id": 325,
    "filename": "68dcc60a4897c.png",
    "name": "XinhhAirlines",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 588,
        "y": 44,
        "w": 508,
        "h": 688
      },
      {
        "x": 44,
        "y": 48,
        "w": 512,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 684
      },
      {
        "x": 588,
        "y": 764,
        "w": 508,
        "h": 684
      }
    ]
  },
  {
    "id": 327,
    "filename": "68dcc67d7e7ab.png",
    "name": "XinhhAirlines",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 3,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      }
    ]
  },
  {
    "id": 333,
    "filename": "68dd4388c0191.png",
    "name": "ToyStory",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 76,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 684,
        "w": 756,
        "h": 552
      },
      {
        "x": 68,
        "y": 1296,
        "w": 756,
        "h": 548
      },
      {
        "x": 64,
        "y": 1908,
        "w": 756,
        "h": 548
      }
    ]
  },
  {
    "id": 334,
    "filename": "68dd4f8543881.png",
    "name": "TV",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 3,
    "slots_data": [
      {
        "x": 124,
        "y": 692,
        "w": 628,
        "h": 496
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 335,
    "filename": "68df3dfdefc22.png",
    "name": "Basic-5",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 508,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 684
      },
      {
        "x": 588,
        "y": 764,
        "w": 508,
        "h": 684
      }
    ]
  },
  {
    "id": 336,
    "filename": "68df3e1149dce.png",
    "name": "Basic-4",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 508,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 684
      },
      {
        "x": 588,
        "y": 764,
        "w": 508,
        "h": 684
      }
    ]
  },
  {
    "id": 337,
    "filename": "68df3e1e7dabf.png",
    "name": "Basic-3",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 508,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 684
      },
      {
        "x": 588,
        "y": 764,
        "w": 508,
        "h": 684
      }
    ]
  },
  {
    "id": 338,
    "filename": "68df3ed02d775.png",
    "name": "Basic-2",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 684
      },
      {
        "x": 588,
        "y": 764,
        "w": 512,
        "h": 684
      }
    ]
  },
  {
    "id": 339,
    "filename": "68df3f19d9d3f.png",
    "name": "Basic-1",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 684
      },
      {
        "x": 588,
        "y": 764,
        "w": 512,
        "h": 684
      }
    ]
  },
  {
    "id": 340,
    "filename": "68df4196da89b.png",
    "name": "Basic-1",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 341,
    "filename": "68df41b70eb0e.png",
    "name": "Basic-2",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 342,
    "filename": "68df41df4934f.png",
    "name": "Basic-7",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 343,
    "filename": "68df420421b73.png",
    "name": "Basic-8",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 345,
    "filename": "68df4242dfa05.png",
    "name": "Basic-11",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 346,
    "filename": "68df42a174a8d.png",
    "name": "Basic-10",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 568
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 347,
    "filename": "68df435872c67.png",
    "name": "Basic-6",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 508,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 684
      },
      {
        "x": 588,
        "y": 764,
        "w": 508,
        "h": 684
      }
    ]
  },
  {
    "id": 348,
    "filename": "68df437c5f891.png",
    "name": "Basic-7",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 684
      },
      {
        "x": 588,
        "y": 764,
        "w": 512,
        "h": 684
      }
    ]
  },
  {
    "id": 349,
    "filename": "68df473214183.png",
    "name": "Basic-1",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 392
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 444,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 392
      }
    ]
  },
  {
    "id": 350,
    "filename": "68df474dba196.png",
    "name": "Basic-2",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 444,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 392
      }
    ]
  },
  {
    "id": 351,
    "filename": "68df4764cfc2b.png",
    "name": "Basic-3",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 444,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 392
      }
    ]
  },
  {
    "id": 352,
    "filename": "68df477dd5360.png",
    "name": "Basic-4",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 444,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 392
      }
    ]
  },
  {
    "id": 353,
    "filename": "68df47965d96e.png",
    "name": "Basic-5",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 392
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 444,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 392
      }
    ]
  },
  {
    "id": 354,
    "filename": "68df47ae9c158.png",
    "name": "Basic-6",
    "frame": "bigrectangle",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 392
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 444,
        "w": 524,
        "h": 388
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 392
      },
      {
        "x": 572,
        "y": 856,
        "w": 524,
        "h": 392
      }
    ]
  },
  {
    "id": 358,
    "filename": "68e471275df2c.png",
    "name": "Colorful",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 68,
        "y": 76,
        "w": 748,
        "h": 544
      },
      {
        "x": 68,
        "y": 688,
        "w": 748,
        "h": 544
      },
      {
        "x": 68,
        "y": 1300,
        "w": 752,
        "h": 544
      },
      {
        "x": 68,
        "y": 1912,
        "w": 752,
        "h": 544
      }
    ]
  },
  {
    "id": 364,
    "filename": "68e4dff09e6d5.png",
    "name": "Jisoo",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 365,
    "filename": "68e4e44d42393.png",
    "name": "BlackPink",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 6,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 560
      },
      {
        "x": 56,
        "y": 680,
        "w": 772,
        "h": 564
      },
      {
        "x": 376,
        "y": 1000,
        "w": 128,
        "h": 184
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      },
      {
        "x": 332,
        "y": 2308,
        "w": 120,
        "h": 160
      }
    ]
  },
  {
    "id": 375,
    "filename": "68e67ec98245f.png",
    "name": "Jin(BTS)",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 377,
    "filename": "68e73af797a67.png",
    "name": "Jimin(BTS)",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 379,
    "filename": "68e8e901bae50.png",
    "name": "Girly",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 568
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 385,
    "filename": "68ecec87142ee.png",
    "name": "Tinder",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 568
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 386,
    "filename": "68f20a3689a97.png",
    "name": "BAV",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học",
    "slots": 3,
    "slots_data": [
      {
        "x": 60,
        "y": 680,
        "w": 764,
        "h": 560
      },
      {
        "x": 64,
        "y": 1296,
        "w": 760,
        "h": 556
      },
      {
        "x": 60,
        "y": 1908,
        "w": 764,
        "h": 556
      }
    ]
  },
  {
    "id": 387,
    "filename": "68f213652773c.png",
    "name": "AOF",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học",
    "slots": 3,
    "slots_data": [
      {
        "x": 60,
        "y": 680,
        "w": 764,
        "h": 560
      },
      {
        "x": 64,
        "y": 1296,
        "w": 760,
        "h": 556
      },
      {
        "x": 60,
        "y": 1908,
        "w": 764,
        "h": 556
      }
    ]
  },
  {
    "id": 388,
    "filename": "68f2143f188f8.png",
    "name": "FTU",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học",
    "slots": 3,
    "slots_data": [
      {
        "x": 60,
        "y": 680,
        "w": 764,
        "h": 560
      },
      {
        "x": 64,
        "y": 1296,
        "w": 760,
        "h": 556
      },
      {
        "x": 60,
        "y": 1908,
        "w": 764,
        "h": 556
      }
    ]
  },
  {
    "id": 389,
    "filename": "68f215d332a18.png",
    "name": "NEU",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học",
    "slots": 3,
    "slots_data": [
      {
        "x": 60,
        "y": 680,
        "w": 764,
        "h": 560
      },
      {
        "x": 64,
        "y": 1296,
        "w": 760,
        "h": 556
      },
      {
        "x": 60,
        "y": 1908,
        "w": 764,
        "h": 556
      }
    ]
  },
  {
    "id": 390,
    "filename": "68f216916ea97.png",
    "name": "HNUE",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học",
    "slots": 3,
    "slots_data": [
      {
        "x": 60,
        "y": 680,
        "w": 764,
        "h": 560
      },
      {
        "x": 64,
        "y": 1296,
        "w": 760,
        "h": 556
      },
      {
        "x": 60,
        "y": 1908,
        "w": 764,
        "h": 556
      }
    ]
  },
  {
    "id": 413,
    "filename": "68f762788685d.png",
    "name": "Dear Phúc Nguyên",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 172,
        "y": 200,
        "w": 2408,
        "h": 1768
      },
      {
        "x": 172,
        "y": 2116,
        "w": 2408,
        "h": 1764
      },
      {
        "x": 176,
        "y": 4028,
        "w": 2408,
        "h": 1764
      },
      {
        "x": 172,
        "y": 5940,
        "w": 2408,
        "h": 1764
      }
    ]
  },
  {
    "id": 427,
    "filename": "68fdab4e38d77.png",
    "name": "ZEUS TBTW",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 60,
        "y": 144,
        "w": 756,
        "h": 492
      },
      {
        "x": 60,
        "y": 724,
        "w": 752,
        "h": 496
      },
      {
        "x": 60,
        "y": 1312,
        "w": 756,
        "h": 504
      },
      {
        "x": 60,
        "y": 1900,
        "w": 756,
        "h": 500
      }
    ]
  },
  {
    "id": 431,
    "filename": "69020f0f64a7c.png",
    "name": "HAU",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học",
    "slots": 3,
    "slots_data": [
      {
        "x": 60,
        "y": 680,
        "w": 764,
        "h": 560
      },
      {
        "x": 64,
        "y": 1296,
        "w": 760,
        "h": 556
      },
      {
        "x": 60,
        "y": 1908,
        "w": 764,
        "h": 556
      }
    ]
  },
  {
    "id": 441,
    "filename": "69024313f210d.png",
    "name": "V(BTS)",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 3,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 568
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 56,
        "y": 1292,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 455,
    "filename": "69097d8bcc7b7.png",
    "name": "Magazine",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 44,
        "y": 768,
        "w": 512,
        "h": 680
      },
      {
        "x": 588,
        "y": 768,
        "w": 512,
        "h": 680
      }
    ]
  },
  {
    "id": 461,
    "filename": "690dcf7ed31b6.png",
    "name": "TMU",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học",
    "slots": 3,
    "slots_data": [
      {
        "x": 60,
        "y": 680,
        "w": 764,
        "h": 560
      },
      {
        "x": 64,
        "y": 1296,
        "w": 760,
        "h": 556
      },
      {
        "x": 60,
        "y": 1908,
        "w": 764,
        "h": 556
      }
    ]
  },
  {
    "id": 462,
    "filename": "690dd37aca67e.png",
    "name": "HMU",
    "frame": "square",
    "categoryId": 53059,
    "categoryName": "Frame Đại Học",
    "slots": 3,
    "slots_data": [
      {
        "x": 60,
        "y": 680,
        "w": 764,
        "h": 560
      },
      {
        "x": 64,
        "y": 1296,
        "w": 760,
        "h": 556
      },
      {
        "x": 60,
        "y": 1908,
        "w": 764,
        "h": 556
      }
    ]
  },
  {
    "id": 465,
    "filename": "6910bc26e14da.png",
    "name": "ParkBoGum",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 560
      },
      {
        "x": 56,
        "y": 680,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 470,
    "filename": "6921c4526b985.png",
    "name": "Steven Universe",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 471,
    "filename": "6921c4677562b.png",
    "name": "matcha",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 568
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 472,
    "filename": "6928ddb90cc97.png",
    "name": "cream-soda",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 56,
        "y": 1292,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 473,
    "filename": "6928ddc669493.png",
    "name": "cream-soda",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 684
      },
      {
        "x": 588,
        "y": 764,
        "w": 512,
        "h": 684
      }
    ]
  },
  {
    "id": 474,
    "filename": "6929d01fd3d8c.png",
    "name": "glorious.blue.eyed.king",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 478,
    "filename": "692c31d942db2.png",
    "name": "Martin",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 4,
    "slots_data": [
      {
        "x": 228,
        "y": 68,
        "w": 600,
        "h": 560
      },
      {
        "x": 56,
        "y": 680,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 479,
    "filename": "692c32375296f.png",
    "name": "Keonho",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 560
      },
      {
        "x": 56,
        "y": 680,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 482,
    "filename": "692d7d65603ca.png",
    "name": "Basic-5",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 564
      },
      {
        "x": 60,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1908,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 483,
    "filename": "692d81cfb1e9f.png",
    "name": "Theater Ticket",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 3,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 568
      },
      {
        "x": 56,
        "y": 1292,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 484,
    "filename": "692d8418563a1.png",
    "name": "Zootopia",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 560
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 1288,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 1900,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 486,
    "filename": "692e9bec9d990.png",
    "name": "BMKTCR x \"BÁO\" THỨC IN ĐẬM INDIE",
    "frame": "square",
    "categoryId": 97804,
    "categoryName": "Frame Sự Kiện",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 768,
        "h": 560
      },
      {
        "x": 56,
        "y": 680,
        "w": 768,
        "h": 560
      },
      {
        "x": 64,
        "y": 1292,
        "w": 720,
        "h": 560
      },
      {
        "x": 56,
        "y": 1904,
        "w": 768,
        "h": 560
      }
    ]
  },
  {
    "id": 491,
    "filename": "692ed2cc19d03.png",
    "name": "Locket",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 1288,
        "w": 772,
        "h": 564
      },
      {
        "x": 56,
        "y": 1912,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 492,
    "filename": "692edb205f3f0.png",
    "name": "seonghyeon",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 560
      },
      {
        "x": 56,
        "y": 680,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 493,
    "filename": "69310c3abb836.png",
    "name": "Merry Chirstmas 🎅🏻",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 100,
        "y": 104,
        "w": 400,
        "h": 576
      },
      {
        "x": 640,
        "y": 104,
        "w": 404,
        "h": 576
      },
      {
        "x": 100,
        "y": 816,
        "w": 400,
        "h": 580
      },
      {
        "x": 628,
        "y": 816,
        "w": 404,
        "h": 580
      }
    ]
  },
  {
    "id": 495,
    "filename": "69310e3a32eac.png",
    "name": "Merry Chirstmas 🎅🏻",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 680,
        "w": 768,
        "h": 564
      },
      {
        "x": 60,
        "y": 1288,
        "w": 768,
        "h": 564
      },
      {
        "x": 60,
        "y": 1912,
        "w": 768,
        "h": 564
      }
    ]
  },
  {
    "id": 496,
    "filename": "6933cabb1dd7d.png",
    "name": "DẤU VÂN TAY x \"BÁO\" THỨC IN ĐẬM INDIE",
    "frame": "square",
    "categoryId": 97804,
    "categoryName": "Frame Sự Kiện",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 768,
        "h": 540
      },
      {
        "x": 56,
        "y": 680,
        "w": 768,
        "h": 560
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 560
      },
      {
        "x": 56,
        "y": 1904,
        "w": 768,
        "h": 560
      }
    ]
  },
  {
    "id": 500,
    "filename": "69403bba702c9.png",
    "name": "CHIPANDCOD x \"BÁO\" THỨC IN ĐẬM INDIE",
    "frame": "square",
    "categoryId": 97804,
    "categoryName": "Frame Sự Kiện",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 768,
        "h": 560
      },
      {
        "x": 56,
        "y": 680,
        "w": 768,
        "h": 560
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 560
      },
      {
        "x": 56,
        "y": 1904,
        "w": 768,
        "h": 560
      }
    ]
  },
  {
    "id": 504,
    "filename": "694f7262a03db.png",
    "name": "Girly",
    "frame": "grid",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 44,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 44,
        "w": 508,
        "h": 688
      },
      {
        "x": 44,
        "y": 764,
        "w": 512,
        "h": 688
      },
      {
        "x": 588,
        "y": 764,
        "w": 508,
        "h": 688
      }
    ]
  },
  {
    "id": 506,
    "filename": "69567d1275bf7.png",
    "name": "Magazine",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 560
      },
      {
        "x": 56,
        "y": 680,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 507,
    "filename": "69567d8355fe2.png",
    "name": "2026",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 64,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 676,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 568
      },
      {
        "x": 60,
        "y": 1908,
        "w": 768,
        "h": 568
      }
    ]
  },
  {
    "id": 508,
    "filename": "69567e9b50731.png",
    "name": "Jang Wonyoung",
    "frame": "square",
    "categoryId": 71668,
    "categoryName": "Frame Chụp Cùng Idol",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 68,
        "w": 772,
        "h": 560
      },
      {
        "x": 56,
        "y": 680,
        "w": 772,
        "h": 564
      },
      {
        "x": 60,
        "y": 1292,
        "w": 768,
        "h": 564
      },
      {
        "x": 56,
        "y": 1904,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 509,
    "filename": "69567fdb48069.png",
    "name": "2026",
    "frame": "bigrectangle",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 6,
    "slots_data": [
      {
        "x": 28,
        "y": 28,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 28,
        "w": 524,
        "h": 388
      },
      {
        "x": 572,
        "y": 440,
        "w": 524,
        "h": 392
      },
      {
        "x": 28,
        "y": 444,
        "w": 520,
        "h": 388
      },
      {
        "x": 572,
        "y": 848,
        "w": 524,
        "h": 392
      },
      {
        "x": 28,
        "y": 856,
        "w": 520,
        "h": 392
      }
    ]
  },
  {
    "id": 510,
    "filename": "69573a0edf0dc.png",
    "name": "Báo Xuân Bính Ngọ",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 68,
        "y": 104,
        "w": 744,
        "h": 520
      },
      {
        "x": 56,
        "y": 676,
        "w": 772,
        "h": 564
      },
      {
        "x": 72,
        "y": 1304,
        "w": 744,
        "h": 536
      },
      {
        "x": 56,
        "y": 1900,
        "w": 772,
        "h": 564
      }
    ]
  },
  {
    "id": 511,
    "filename": "695b91d10ae9f.png",
    "name": "Doggo's Day",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 84,
        "y": 124,
        "w": 788,
        "h": 568
      },
      {
        "x": 92,
        "y": 776,
        "w": 776,
        "h": 568
      },
      {
        "x": 84,
        "y": 1428,
        "w": 784,
        "h": 592
      },
      {
        "x": 132,
        "y": 2152,
        "w": 728,
        "h": 532
      }
    ]
  },
  {
    "id": 515,
    "filename": "696a75a998902.png",
    "name": "UmTi9thdebut",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 52,
        "y": 56,
        "w": 496,
        "h": 364
      },
      {
        "x": 56,
        "y": 472,
        "w": 496,
        "h": 356
      },
      {
        "x": 56,
        "y": 888,
        "w": 496,
        "h": 328
      },
      {
        "x": 52,
        "y": 1304,
        "w": 496,
        "h": 300
      }
    ]
  },
  {
    "id": 522,
    "filename": "698eb32be5f3e.png",
    "name": "tripleS 3rd anniversary",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 152,
        "y": 172,
        "w": 1704,
        "h": 1240
      },
      {
        "x": 144,
        "y": 1552,
        "w": 1708,
        "h": 1268
      },
      {
        "x": 156,
        "y": 2952,
        "w": 1680,
        "h": 1264
      },
      {
        "x": 156,
        "y": 4356,
        "w": 1688,
        "h": 1252
      }
    ]
  },
  {
    "id": 524,
    "filename": "6992b4f935784.png",
    "name": "digitalcam cartoon",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 180,
        "w": 604,
        "h": 380
      },
      {
        "x": 60,
        "y": 756,
        "w": 536,
        "h": 432
      },
      {
        "x": 52,
        "y": 1412,
        "w": 528,
        "h": 404
      },
      {
        "x": 112,
        "y": 1988,
        "w": 560,
        "h": 424
      }
    ]
  },
  {
    "id": 525,
    "filename": "6999b129e6732.png",
    "name": "⪩. .⪨ 𝐂𝐞𝐥𝐞𝐛𝐫𝐚𝐭𝐞 “𝓟𝓮𝓪𝓷𝓾𝓽” 𝟏𝟏𝐭𝐡 𝐝𝐞𝐛𝐮𝐭: 🥜",
    "frame": "square",
    "categoryId": 97804,
    "categoryName": "Frame Sự Kiện",
    "slots": 4,
    "slots_data": [
      {
        "x": 60,
        "y": 60,
        "w": 560,
        "h": 328
      },
      {
        "x": 104,
        "y": 512,
        "w": 476,
        "h": 444
      },
      {
        "x": 64,
        "y": 1012,
        "w": 556,
        "h": 384
      },
      {
        "x": 64,
        "y": 1488,
        "w": 552,
        "h": 356
      }
    ]
  },
  {
    "id": 526,
    "filename": "699c22078a038.png",
    "name": "Shane Hollander",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 96,
        "y": 108,
        "w": 692,
        "h": 532
      },
      {
        "x": 76,
        "y": 716,
        "w": 624,
        "h": 508
      },
      {
        "x": 104,
        "y": 1328,
        "w": 688,
        "h": 512
      },
      {
        "x": 104,
        "y": 1944,
        "w": 672,
        "h": 440
      }
    ]
  },
  {
    "id": 528,
    "filename": "699e0fa10f0f8.png",
    "name": "HLE25 x camjack",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 224,
        "y": 328,
        "w": 1052,
        "h": 556
      },
      {
        "x": 168,
        "y": 1160,
        "w": 1156,
        "h": 668
      },
      {
        "x": 284,
        "y": 2368,
        "w": 944,
        "h": 464
      },
      {
        "x": 196,
        "y": 3252,
        "w": 1116,
        "h": 560
      }
    ]
  },
  {
    "id": 529,
    "filename": "699e172e8caa3.png",
    "name": "LLYA Rozanov",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 96,
        "y": 108,
        "w": 692,
        "h": 532
      },
      {
        "x": 76,
        "y": 716,
        "w": 624,
        "h": 508
      },
      {
        "x": 104,
        "y": 1328,
        "w": 688,
        "h": 512
      },
      {
        "x": 104,
        "y": 1944,
        "w": 672,
        "h": 440
      }
    ]
  },
  {
    "id": 530,
    "filename": "699e18009131a.png",
    "name": "Hoàng Yến Chibi",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 56,
        "y": 80,
        "w": 596,
        "h": 356
      },
      {
        "x": 52,
        "y": 476,
        "w": 608,
        "h": 356
      },
      {
        "x": 56,
        "y": 876,
        "w": 584,
        "h": 356
      },
      {
        "x": 56,
        "y": 1276,
        "w": 600,
        "h": 356
      }
    ]
  },
  {
    "id": 531,
    "filename": "699e18607041b.png",
    "name": "Dương Domic",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 32,
        "y": 52,
        "w": 388,
        "h": 216
      },
      {
        "x": 32,
        "y": 304,
        "w": 388,
        "h": 216
      },
      {
        "x": 32,
        "y": 556,
        "w": 388,
        "h": 216
      },
      {
        "x": 32,
        "y": 812,
        "w": 388,
        "h": 212
      }
    ]
  },
  {
    "id": 532,
    "filename": "69ac4f1c3282f.png",
    "name": "아가공'𝑠 𝑂𝑑𝑦𝑠𝑠𝑒𝑦 — ZEKA",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 64,
        "y": 292,
        "w": 716,
        "h": 468
      },
      {
        "x": 60,
        "y": 844,
        "w": 716,
        "h": 468
      },
      {
        "x": 56,
        "y": 1404,
        "w": 724,
        "h": 476
      },
      {
        "x": 60,
        "y": 2028,
        "w": 716,
        "h": 400
      }
    ]
  },
  {
    "id": 533,
    "filename": "69ac4f2346868.png",
    "name": "아가공'𝑠 𝑂𝑑𝑦𝑠𝑠𝑒𝑦 — ZEKA",
    "frame": "grid",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 176,
        "y": 260,
        "w": 604,
        "h": 992
      },
      {
        "x": 884,
        "y": 260,
        "w": 608,
        "h": 1036
      },
      {
        "x": 892,
        "y": 1404,
        "w": 600,
        "h": 924
      },
      {
        "x": 176,
        "y": 1412,
        "w": 604,
        "h": 916
      }
    ]
  },
  {
    "id": 534,
    "filename": "69ae27bd104bf.png",
    "name": "thomeo",
    "frame": "square",
    "categoryId": 59563,
    "categoryName": "Frame Cartoon",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 72,
        "w": 624,
        "h": 376
      },
      {
        "x": 44,
        "y": 468,
        "w": 624,
        "h": 376
      },
      {
        "x": 44,
        "y": 868,
        "w": 624,
        "h": 372
      },
      {
        "x": 44,
        "y": 1264,
        "w": 624,
        "h": 376
      }
    ]
  },
  {
    "id": 535,
    "filename": "69ae27cf2e4e8.png",
    "name": "Pháp Kiều",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 60,
        "y": 76,
        "w": 592,
        "h": 348
      },
      {
        "x": 64,
        "y": 468,
        "w": 588,
        "h": 364
      },
      {
        "x": 56,
        "y": 868,
        "w": 596,
        "h": 364
      },
      {
        "x": 44,
        "y": 1268,
        "w": 612,
        "h": 376
      }
    ]
  },
  {
    "id": 536,
    "filename": "69ae287abfeb9.png",
    "name": "Phúc Nguyên",
    "frame": "square",
    "categoryId": 42245,
    "categoryName": "Frame IDOL Hoạt Họa",
    "slots": 4,
    "slots_data": [
      {
        "x": 280,
        "y": 384,
        "w": 3224,
        "h": 1992
      },
      {
        "x": 248,
        "y": 2564,
        "w": 3276,
        "h": 1896
      },
      {
        "x": 316,
        "y": 4676,
        "w": 3188,
        "h": 1916
      },
      {
        "x": 276,
        "y": 6788,
        "w": 3224,
        "h": 1876
      }
    ]
  },
  {
    "id": 537,
    "filename": "69ae2892b1b59.png",
    "name": "Birthday Party",
    "frame": "square",
    "categoryId": 34603,
    "categoryName": "Frame Amazing ⭐️",
    "slots": 4,
    "slots_data": [
      {
        "x": 48,
        "y": 76,
        "w": 612,
        "h": 372
      },
      {
        "x": 48,
        "y": 476,
        "w": 612,
        "h": 364
      },
      {
        "x": 48,
        "y": 868,
        "w": 612,
        "h": 372
      },
      {
        "x": 48,
        "y": 1272,
        "w": 612,
        "h": 364
      }
    ]
  },
  {
    "id": 538,
    "filename": "69ae28ab885ab.png",
    "name": "Save the date",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 156,
        "y": 104,
        "w": 676,
        "h": 588
      },
      {
        "x": 148,
        "y": 784,
        "w": 676,
        "h": 608
      },
      {
        "x": 144,
        "y": 1468,
        "w": 672,
        "h": 612
      },
      {
        "x": 148,
        "y": 2176,
        "w": 676,
        "h": 592
      }
    ]
  },
  {
    "id": 539,
    "filename": "69ae28bd7352b.png",
    "name": "star1",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 72,
        "y": 84,
        "w": 860,
        "h": 644
      },
      {
        "x": 72,
        "y": 772,
        "w": 860,
        "h": 644
      },
      {
        "x": 72,
        "y": 1464,
        "w": 860,
        "h": 644
      },
      {
        "x": 72,
        "y": 2152,
        "w": 860,
        "h": 644
      }
    ]
  },
  {
    "id": 540,
    "filename": "69ae28caab9c6.png",
    "name": "star2",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 32,
        "y": 32,
        "w": 936,
        "h": 704
      },
      {
        "x": 32,
        "y": 780,
        "w": 936,
        "h": 700
      },
      {
        "x": 32,
        "y": 1524,
        "w": 936,
        "h": 700
      },
      {
        "x": 32,
        "y": 2268,
        "w": 936,
        "h": 700
      }
    ]
  },
  {
    "id": 541,
    "filename": "69ae2913e9287.png",
    "name": "star3",
    "frame": "square",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 44,
        "y": 72,
        "w": 912,
        "h": 680
      },
      {
        "x": 48,
        "y": 780,
        "w": 908,
        "h": 680
      },
      {
        "x": 44,
        "y": 1488,
        "w": 912,
        "h": 680
      },
      {
        "x": 48,
        "y": 2196,
        "w": 908,
        "h": 684
      }
    ]
  },
  {
    "id": 542,
    "filename": "69ae292690b2f.png",
    "name": "hpbd",
    "frame": "grid",
    "categoryId": 62459,
    "categoryName": "Frame Basic",
    "slots": 4,
    "slots_data": [
      {
        "x": 84,
        "y": 84,
        "w": 648,
        "h": 864
      },
      {
        "x": 772,
        "y": 84,
        "w": 648,
        "h": 864
      },
      {
        "x": 84,
        "y": 988,
        "w": 648,
        "h": 864
      },
      {
        "x": 824,
        "y": 1072,
        "w": 568,
        "h": 708
      }
    ]
  }
]
