/**
 * Detect transparent slot count in each frame PNG using a flood-fill DFS (same
 * algorithm as imageProcessing.ts but in Node.js with pngjs).
 *
 * Adds/updates the `slots` field on every entry in STATIC_FRAMES and rewrites
 * src/lib/frames-static.ts.
 *
 * Run: node scripts/detect-slots.mjs
 */
import { readFileSync, writeFileSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { PNG } from 'pngjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const FRAMES_DIR = path.join(ROOT, 'public', 'frames')
const OUTPUT_FILE = path.join(ROOT, 'src', 'lib', 'frames-static.ts')

// ── Same DFS flood-fill as imageProcessing.ts ────────────────────────────────

function detectSlotsFromPng(pngData) {
    const { width: W, height: H, data } = pngData

    // Downsample 4× for speed
    const SCALE = 0.25
    const sw = Math.max(1, Math.round(W * SCALE))
    const sh = Math.max(1, Math.round(H * SCALE))

    // Build downsampled alpha channel by averaging
    const alpha = new Uint8Array(sw * sh)
    for (let sy = 0; sy < sh; sy++) {
        for (let sx = 0; sx < sw; sx++) {
            // Map to source pixel (nearest neighbour)
            const sx0 = Math.round(sx / SCALE)
            const sy0 = Math.round(sy / SCALE)
            const srcX = Math.min(sx0, W - 1)
            const srcY = Math.min(sy0, H - 1)
            const idx = (srcY * W + srcX) * 4
            alpha[sy * sw + sx] = data[idx + 3]
        }
    }

    const ALPHA_THRESH = 10
    const minArea = Math.max(4, Math.round(sw * sh * 0.005))

    const trans = new Uint8Array(sw * sh)
    const visited = new Uint8Array(sw * sh)
    for (let i = 0; i < sw * sh; i++) {
        if (alpha[i] < ALPHA_THRESH) trans[i] = 1
    }

    const slots = []

    for (let start = 0; start < sw * sh; start++) {
        if (!trans[start] || visited[start]) continue

        const stack = [start]
        visited[start] = 1
        let minX = sw, maxX = 0, minY = sh, maxY = 0
        let area = 0

        while (stack.length) {
            const idx = stack.pop()
            const px = idx % sw
            const py = (idx / sw) | 0
            if (px < minX) minX = px
            if (px > maxX) maxX = px
            if (py < minY) minY = py
            if (py > maxY) maxY = py
            area++

            if (px > 0) { const n = idx - 1; if (trans[n] && !visited[n]) { visited[n] = 1; stack.push(n) } }
            if (px < sw - 1) { const n = idx + 1; if (trans[n] && !visited[n]) { visited[n] = 1; stack.push(n) } }
            if (py > 0) { const n = idx - sw; if (trans[n] && !visited[n]) { visited[n] = 1; stack.push(n) } }
            if (py < sh - 1) { const n = idx + sw; if (trans[n] && !visited[n]) { visited[n] = 1; stack.push(n) } }
        }

        if (area >= minArea) {
            slots.push({ minX, maxX, minY, maxY })
        }
    }

    return slots.length
}

// ── Read existing STATIC_FRAMES from the generated .ts file ──────────────────

function parseStaticFrames(ts) {
    // Extract the JSON array literal from the TS source
    const match = ts.match(/export const STATIC_FRAMES[^=]*=\s*(\[[\s\S]*\])\s*\n?$/)
    if (!match) throw new Error('Could not parse STATIC_FRAMES from frames-static.ts')
    return JSON.parse(match[1])
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
    const ts = readFileSync(OUTPUT_FILE, 'utf8')
    const frames = parseStaticFrames(ts)
    console.log(`📋 ${frames.length} frames to process`)

    let ok = 0, fail = 0

    for (const frame of frames) {
        const pngPath = path.join(FRAMES_DIR, frame.filename)
        try {
            const buf = readFileSync(pngPath)
            const png = PNG.sync.read(buf)
            const count = detectSlotsFromPng(png)
            frame.slots = count
            ok++
            if (ok % 20 === 0 || ok === frames.length) {
                process.stdout.write(`\r   ${ok}/${frames.length} processed`)
            }
        } catch (err) {
            frame.slots = 0
            fail++
            console.error(`\n   ✗ ${frame.filename}: ${err.message}`)
        }
    }

    console.log(`\n\n✅ Done: ${ok} ok, ${fail} failed`)

    // Log summary of slot counts found
    const counts = {}
    for (const f of frames) counts[f.slots] = (counts[f.slots] ?? 0) + 1
    console.log('   Slot distribution:', Object.entries(counts).sort(([a], [b]) => +a - +b).map(([k, v]) => `${k} slots: ${v}`).join(', '))

    // Rewrite frames-static.ts
    const newTs = `// AUTO-GENERATED by scripts/download-frames.mjs + detect-slots.mjs — do not edit manually
import type { FrameItem } from './frameService'

export const STATIC_FRAMES: FrameItem[] = ${JSON.stringify(frames, null, 2)}
`
    writeFileSync(OUTPUT_FILE, newTs, 'utf8')
    console.log(`📄 Updated src/lib/frames-static.ts with slot counts`)
}

main().catch(err => { console.error(err); process.exit(1) })
