/**
 * Download all frames from cdn.freehihi.com and generate a static data file.
 * Run: node scripts/download-frames.mjs
 */
import { mkdir, writeFile } from 'fs/promises'
import { existsSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const FRAMES_DIR = path.join(ROOT, 'public', 'frames')
const OUTPUT_FILE = path.join(ROOT, 'src', 'lib', 'frames-static.ts')
const API_URL = 'https://photo.freehihi.com/api/images'
const CDN_BASE = 'https://cdn.freehihi.com'

function deriveCategoryId(name) {
    let h = 0
    for (let i = 0; i < name.length; i++) h = Math.imul(31, h) + name.charCodeAt(i) | 0
    return Math.abs(h) % 90000 + 10000
}

async function fetchWithRetry(url, attempts = 3) {
    for (let i = 0; i < attempts; i++) {
        try {
            const res = await fetch(url)
            if (!res.ok) throw new Error(`HTTP ${res.status}`)
            return res
        } catch (err) {
            if (i === attempts - 1) throw err
            await new Promise(r => setTimeout(r, 1000 * (i + 1)))
        }
    }
}

async function main() {
    console.log('📡 Fetching frame list...')
    const res = await fetchWithRetry(API_URL)
    const frames = await res.json()
    console.log(`   Got ${frames.length} frames`)

    await mkdir(FRAMES_DIR, { recursive: true })

    const results = []
    let ok = 0, skip = 0, fail = 0

    for (const frame of frames) {
        const dest = path.join(FRAMES_DIR, frame.filename)
        if (existsSync(dest)) {
            skip++
            results.push(frame)
            process.stdout.write(`\r   ✓ ${ok + skip}/${frames.length} (${skip} cached)`)
            continue
        }
        try {
            const imgRes = await fetchWithRetry(`${CDN_BASE}/${frame.filename}`)
            const buf = Buffer.from(await imgRes.arrayBuffer())
            await writeFile(dest, buf)
            ok++
            results.push(frame)
        } catch (err) {
            fail++
            console.error(`\n   ✗ Failed: ${frame.filename} — ${err.message}`)
        }
        process.stdout.write(`\r   ↓ ${ok + skip}/${frames.length} downloaded`)
    }

    console.log(`\n\n✅ Done: ${ok} downloaded, ${skip} cached, ${fail} failed`)

    // Generate static TypeScript file
    const ts = `// AUTO-GENERATED by scripts/download-frames.mjs — do not edit manually
import type { FrameItem } from './frameService'

export const STATIC_FRAMES: FrameItem[] = ${JSON.stringify(
        results.map(f => {
            const catName = f.category?.name ?? 'Khác'
            return {
                id: f.id,
                filename: f.filename,
                name: f.name,
                frame: f.frame,
                categoryId: deriveCategoryId(catName),
                categoryName: catName,
            }
        }),
        null,
        2
    )}
`
    await writeFile(OUTPUT_FILE, ts, 'utf8')
    console.log(`📄 Static data written to src/lib/frames-static.ts`)
}

main().catch(err => { console.error(err); process.exit(1) })
